### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by seabbs** [jbracher/branching_process_delta#4]
This looks good and all sensible. 

Various thoughts below: 

- Why do the variants have different reporting processes in case notifications? I would probably have a single reporting process for cases or pull the over-dispersion from a pooled parameter to share power. 
- Similarly having the two variants have fully independent random walks may not be ideal (or it may ;)). I've seen other implementations that assume a baseline Rt that walks over time and then fits a scaling modifier to get a variant Rt. You could use a hybrid of this approach by having the modifier also walk over time. This change might lead to some issues without imports. 
- As noted in your twitter thread the dates of the sequenced cases and notified cases are potentially a bit out of alignment. Difficult to say more than that without knowing the data but I can imagine that there is a perhaps a week delay. Perhaps look at postiivity rate and overall case rate to see if trends match (very rough I realise).
- In write up suggest drop: "fully" from "fully Bayesian model" in the model formulation. 
- Is it reasonable to assume that sampled cases have the same reporting process as notified cases? When I have seen versions of this model before they usually use the mean of notified cases to calculate the sampled cases and then add some independent noise on this. This interpretation depends on if you think the stochastic variation in observed cases is from the infection process or reporting I think so either can be defended.
- Lots of uniform priors. I really hate them because they don't really represent the state of our knowledge. Suggest moving to some truncated Gaussian priors or similar though from my memory JAGs is a bit fussy with priors so maybe driven by this.

**Comment by jbracher** [comment]
Thanks a lot, Sam! Re your comments:
- I guess I could share the overdispersion parameter now. In the beginning I as hesitant as the numbers for the two branching processes where in quite different orders of magnitude.
- I tried a shared random walk first, but that gave sort of weird results. The non-delta counts contribute much more information so the model kind of ignores what's going on with delta when I share these.
- I spent some time thinking about temporal alignment today. RKI themselves are happy to multiply their numbers with the incidence by reporting date to the local authorities (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/DESH/Bericht_VOC_2021-06-30.pdf?__blob=publicationFile, Tab 11). The JHU data agree quite well with these lately, even though I think that they are by reporting date to the national authorities (not quite clear though). So for now I kept it this way, but will try to get some feedback from people more familiar with these data sources.
- Will need to give the question of the reporting process more thought. The model is not very mechanistic anyway as it just operates on a weekly scale while generation times are shorter.
- Uniform priors: I plead guilty ;)

**Comment by seabbs** [comment]
Sounds like you have done the best you can with matching the sequence and reported data. Do you have access to s-gene target failure data as a proxy in Germany? 

For the reporting process, I suppose the ideal would be to have a joint observation model representing infections and then additional uncertainty for both representing the actual reporting process. I imagine that not being able to be identified though. 

Linked PR has a rerolled version implemented in stan based on some of my comments here. In no way a suggestion you use or adopt any of it - just for interest!
